import { Injectable } from '@angular/core';
import { Books } from './shared/book';
import { Tag } from './shared/models/Tag';
@Injectable({
  providedIn: 'root'
})
export class StoreService {

  constructor() { }

 getBookById(id:number){
  return this.getAll().find(book => book.id === String(id))!;
 }

  getAllBookByTag(tag:string) :Books[]{
    return tag == "All"?
    this.getAll() : this.getAll().filter(book =>book.tags?.includes(tag));
    //you can write this statement is very simpletype lets do it.
  }

  getAllTag():Tag[]{
    return[
      {name:'All',count: 20},
      {name:'Fiction',count:17},
      {name:'Non-Fiction',count:11},
      {name:'New Arrivals',count:8},
      {name:'School Education',count:2},
    ];

  }
  getAll():Books[]{
    return[
      {
      name:'Atomic Habbits',
      id:'101',
      author:['James Clear'],
      publisher:'Penguin Random House India Private DeclarationListEmitMode',
      price:559,
      availability:'Available',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :4.0,
      imageUrl:'/assets/front page/f1.jpg',
      aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
      aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
      reviews:'No review found',
      tags:['Atomic Habbits','Non-Fiction','New Arrivals'],
      },
      {
        name:'The Pshycology of Money',
        id:'102',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:279,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f2.jpg',
        aboutTheBook:'Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters.',
        aboutTheAuthor:'Morgan Housel is a partner at The Collaborative Fund and a former columnist at The Motley Fool and The Wall Street Journal. He is a two-time winner of the Best in Business Award from the Society of American Business Editors and Writers, winner of the New York Times Sidney Award, and a two-time finalist for the Gerald Loeb Award for Distinguished Business and Financial Journalism.',
        reviews:'No review Found',
        tags:['The Pshcology of Money','New Arrivals'],
      },
      {
        name:'The Honest Always Stand Alone',
        id:'103',
        author:[''],
        publisher:'',
        price:300,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f3.jpg',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['The Honest Always Stand Alone','New Arrivals'],
      },
      {
        name:'The Shining Mountain',
        id:'104',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:305,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f4.jpg',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['The Shining Mountain','New Arrivals'],
      },
      {
        name:'The World United',
        id:'105',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:279,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f5.jpg',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['The World United','Adventure','New Arrivals'],
      },
      {
        name:'Everyone Has A Story',
        id:'106',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:452,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f6.jfif',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['EveryThing Has a Story','New Arrivals'],
      },
      {
        name:'Attitude is Everything',
        id:'107',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:250,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f7.png',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['Attitude isEverything','New Arrivals'],
      },
      {
        name:'The Eagle',
        id:'108',
        author:['Morgan Housel'],
        publisher:'Jaico Publishing House',
        price:105,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/front page/f8.webp',
        aboutTheBook:'"Atomic Habits" by James Clear is a bestselling self-help book that focuses on the power of small habits and their impact on our lives. It provides a framework for understanding habit formation and offers practical strategies to create positive habits and break negative ones. Clear explores the habit loop, discusses the importance of cues and rewards, and suggests techniques to make habits obvious, attractive, easy, and satisfying. The book also addresses challenges like procrastination and offers advice on staying motivated and overcoming setbacks. "Atomic Habits" is known for its practicality and evidence-based approach, and it has become a popular resource for personal growth and behavior change',
        aboutTheAuthor:'James Clear is an expert on habits and decision making. He made his name as the author of one of the fastest-growing email newsletters in history, which grew from zero to 100,000 subscribers in under two years. Today, his newsletter has over 400,000 subscribers and his articles at jamesclear receive 10 million hits each year. His work frequently appears in publications including the New York Times, Forbes and Business Insider',
        reviews:'No review Found',
        tags:['The Eagle','New Arrivals'],
      },

      // Fiction Books
     //--------------------------- Romance Book ------------------------------------------ 
       {
        name:'Romeo Juliet',
        id:'201',
        author:['Shakespeare'],
        publisher:'Penguin Random House',
        price:300,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/r10.jpg',
        aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
        aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
        reviews:'No review Found',
        tags:['Fiction','Romance','Romeo Juliet','Shakespeare'],
      },
      {
        name:'Will YOu Still Love me?',
        id:'202',
        author:['Ravinder Singh'],
        publisher:'Penguin Random House',
        price:350,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/r1.jpg',
        aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
        aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
        reviews:'No review Found',
        tags:['Fiction','Romance','Will you still love me?','Ravinder Singh'],
      },
      {
      name:'',
        id:'203',
        author:['Savi Sharma'],
        publisher:'Penguin Random House',
        price:400,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/r2.jpeg',
        aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
        aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
        reviews:'No review Found',
        tags:['Fiction','Romance','Everything Has a Story ','Savi Sharma'],
      },

      {
        name:'I Will Never Find Another U',
          id:'204',
          author:['Kumar Kaustubh'],
          publisher:'Penguin Random House',
          price:250,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/r3.jpeg',
          aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
          aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
          reviews:'No review Found',
          tags:['Fiction','Romance','I Will Never Find Another U','Kumar Kaustubh'],
        },

        {
          name:'With You... Without You: Every Friendship Has its Own Story',
            id:'205',
            author:['Kushal Mitra'],
            publisher:'LiFi Publications Pvt Ltd',
            price:350,
            availability:'Availabilty',
            shippingtime:'Usually ships 1-3 Days',
            favorite:false,
            star :5.0,
            imageUrl:'/assets/Romance/r4.jpeg',
            aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
            aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
            reviews:'No review Found',
            tags:['Fiction','Romance','With You... Without You: Every Friendship Has its Own Story','Kushal Mitra'],
          },

          {
            name:'The Perfect Us',
              id:'206',
              author:['Durjoy Datta'],
              publisher:'Penguin Random House India Private Limited',
              price:200,
              availability:'Availabilty',
              shippingtime:'Usually ships 1-3 Days',
              favorite:false,
              star :5.0,
              imageUrl:'/assets/Romance/r5.jpeg',
              aboutTheBook:'',
              aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
              reviews:'No review Found',
              tags:['Fiction','Romance','The Perfect Us','Durjoy Datta'],
            },

            {
              name:'The Boy With a Broken Heart',
                id:'207',
                author:['Durjoy Datta'],
                publisher:'Penguin Random House',
                price:350,
                availability:'Availabilty',
                shippingtime:'Usually ships 1-3 Days',
                favorite:false,
                star :5.0,
                imageUrl:'/assets/Romance/r6.jpeg',
                aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                reviews:'No review Found',
                tags:['Fiction','Romance','The Boy With a Broken Heart','Durjoy Datta'],
              },

              {
                name:'Everyone Has a Story 2',
                  id:'208',
                  author:['Savi Sharma'],
                  publisher:'Penguin Random House',
                  price:350,
                  availability:'Availabilty',
                  shippingtime:'Usually ships 1-3 Days',
                  favorite:false,
                  star :5.0,
                  imageUrl:'/assets/Romance/r7.jpeg',
                  aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                  aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                  reviews:'No review Found',
                  tags:['Fiction','Romance','Everyone Has a Story 2','Savi Sharma'],
                },

                {
                  name:'The Third Eye Of Love',
                    id:'209',
                    author:['K V MohanKumar'],
                    publisher:'Penguin Random House',
                    price:300,
                    availability:'Availabilty',
                    shippingtime:'Usually ships 1-3 Days',
                    favorite:false,
                    star :5.0,
                    imageUrl:'/assets/Romance/r8.jpeg',
                    aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                    aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                    reviews:'No review Found',
                    tags:['Fiction','Romance','The Third Eye Of Love','K V MohanKumar'],
                  },

                  {
                    name:'Marriage Without Marriage',
                      id:'210',
                      author:['S.K.Sood'],
                      publisher:'Penguin Random House',
                      price:300,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'/assets/Romance/r9.jpeg',
                      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                      reviews:'No review Found',
                      tags:['Fiction','Romance','Marriage Without Marriage','S.K.Sood'],
                    },

                    //----------------Adventure Books------------------------

                    {
                      name:'The Time Machine',
                      id:'301',
                      author:['H.G.Wells'],
                      publisher:'Penguin Random House',
                      price:300,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'https://m.media-amazon.com/images/I/71+n2VSAiXS._AC_UY218_.jpg',
                      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
                      aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
                      reviews:'No review Found',
                      tags:['Fiction','Adventure','The Time Machine','H.G.Wells'],
                    },
                    {
                      name:'The Island of Adventure',
                      id:'302',
                      author:['Enid Blyton'],
                      publisher:'Penguin Random House',
                      price:350,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'https://m.media-amazon.com/images/I/91nKidE8MjL._AC_UY218_.jpg',
                      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
                      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
                      reviews:'No review Found',
                      tags:['Fiction','Adventure','The Island of Adventure','Enid Blyton'],
                    },
                    {
                    name:'Complete Adventures of Feluda',
                      id:'203',
                      author:['Satyajit Ray'],
                      publisher:'Penguin Random House',
                      price:400,
                      availability:'Availabilty',
                      shippingtime:'Usually ships 1-3 Days',
                      favorite:false,
                      star :5.0,
                      imageUrl:'https://m.media-amazon.com/images/I/515VOqI0ABL._AC_UY218_.jpg',
                      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
                      aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
                      reviews:'No review Found',
                      tags:['Fiction','Adventure','Complete Adventures of Feluda ','Satyajit Ray'],
                    },
              
                    {
                      name:'Tressure Island',
                        id:'204',
                        author:['Robert Louis Stevenson'],
                        publisher:'Penguin Random House',
                        price:250,
                        availability:'Availabilty',
                        shippingtime:'Usually ships 1-3 Days',
                        favorite:false,
                        star :5.0,
                        imageUrl:'https://m.media-amazon.com/images/I/71+f+GXLk4L._AC_UY218_.jpg',
                        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
                        aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
                        reviews:'No review Found',
                        tags:['Fiction','Adventure','Tressure Island','Robert Louis Stevenson'],
                      },
              
                      {
                        name:'With You... Without You: Every Friendship Has its Own Story',
                          id:'205',
                          author:['Kushal Mitra'],
                          publisher:'LiFi Publications Pvt Ltd',
                          price:350,
                          availability:'Availabilty',
                          shippingtime:'Usually ships 1-3 Days',
                          favorite:false,
                          star :5.0,
                          imageUrl:'/assets/Romance/r4.jpeg',
                          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
                          aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
                          reviews:'No review Found',
                          tags:['Fiction','Adventure','With You... Without You: Every Friendship Has its Own Story','Kushal Mitra'],
                        },
              
                       

//-------------------------Mystery Book --------------------------------------
{
  name:'The Perfect Murder',
  id:'201',
  author:['Ruskin Bond'],
  publisher:'Penguin Random House',
  price:300,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'https://m.media-amazon.com/images/I/81PHdxm0iZL._AC_UY218_.jpg',
  aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
  aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
  reviews:'No review Found',
  tags:['Fiction','Mystery','The Perfect Murder','Ruskin Bond'],
},
{
  name:'The Mystery of the Blue Train',
  id:'202',
  author:['Agatha Christie'],
  publisher:'Penguin Random House',
  price:350,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'https://m.media-amazon.com/images/I/71uDGnrSUyL._AC_UY218_.jpg',
  aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
  aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
  reviews:'No review Found',
  tags:['Fiction','Mystery','The Mystery of the Blue Train','Agatha Christie'],
},
{
name:'The Girl in the House',
  id:'203',
  author:['Harshvardhan Rao'],
  publisher:'Penguin Random House',
  price:400,
  availability:'Availabilty',
  shippingtime:'Usually ships 1-3 Days',
  favorite:false,
  star :5.0,
  imageUrl:'https://m.media-amazon.com/images/I/71G-qUz3TuL._AC_UY218_.jpg',
  aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
  aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
  reviews:'No review Found',
  tags:['Fiction','Mystery','The Girl in the House ','Harsgvardhan Rao'],
},

{
  name:'Cold Blooded Love',
    id:'204',
    author:['Girish Dutt Shukla'],
    publisher:'Penguin Random House',
    price:250,
    availability:'Availabilty',
    shippingtime:'Usually ships 1-3 Days',
    favorite:false,
    star :5.0,
    imageUrl:'https://m.media-amazon.com/images/I/71+Cl8TmXhL._AC_UY218_.jpg',
    aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
    aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
    reviews:'No review Found',
    tags:['Fiction','Mystery','Cold Blooded Love','Girish Dutt Shukla'],
  },

  {
    name:'3 and a Half Murders',
      id:'205',
      author:['Salil Desai'],
      publisher:'LiFi Publications Pvt Ltd',
      price:350,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/71R7xR0-wSL._AC_UY218_.jpg',
      aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
      aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
      reviews:'No review Found',
      tags:['Fiction','Mystery','3 and a Half Murders','Salil Desai'],
    },

    
    //------------------------Fantasy Book -----------------------------
    {
      name:'The Canterville Ghost',
      id:'201',
      author:['Oscar Wilde'],
      publisher:'Penguin Random House',
      price:300,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/713-hV5Oz8L._AC_UY218_.jpg',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Fiction','Fantasy','The Canterville Ghost','Oscar Wilde'],
    },
    {
      name:'The Folk of the Air Series',
      id:'202',
      author:['Black Holly'],
      publisher:'Penguin Random House',
      price:350,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/81ZioG+UUbL._AC_UY218_.jpg',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Fiction','Fantasy','The Folk of the Air Series','Black Holly'],
    },
    {
    name:'The Girl Who Drank the Moon',
      id:'203',
      author:['Kelly Barnhill'],
      publisher:'Penguin Random House',
      price:400,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/7138zaESFhL._AC_UY218_.jpg',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Fiction','Fantasy','The Girl Who Drank The Moon ','Kelly Barnhill'],
    },

    {
      name:'The Sun and the Star',
        id:'204',
        author:['Rick Riordon'],
        publisher:'Penguin Random House',
        price:250,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'https://m.media-amazon.com/images/I/81K2JRIsLRL._AC_UY218_.jpg',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Fiction','Fantasy','The Sun and the Star','Rick Riodan'],
      },

      {
        name:'Journey to the center of the Earth',
          id:'205',
          author:['Jules Verne'],
          publisher:'LiFi Publications Pvt Ltd',
          price:350,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'https://m.media-amazon.com/images/I/712mbINbEML._AC_UY218_.jpg',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Fiction','Fantasy','Journey to the center of the Earth','Jules Verne'],
        },

        
    //---------------------------Children Book---------------------------
    {
      name:'The Ugly Duckling',
      id:'201',
      author:['Navneet'],
      publisher:'Penguin Random House',
      price:300,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://buybooksindia.s3.amazonaws.com/2023/products/9788124317433-1688731102.jpg',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Fiction','Children','The Ugly Duckling','Navneet'],
    },
    {
      name:'Snow white and the 7 Dwarfs',
      id:'202',
      author:['Navneet'],
      publisher:'Penguin Random House',
      price:350,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://buybooksindia.s3.amazonaws.com/2023/products/9788124317440-1688731102.jpg',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Fiction','Children','Snow white and the 7 Dwarfs','Navneet'],
    },
    {
    name:'Cindrella',
      id:'203',
      author:['Navneet'],
      publisher:'Penguin Random House',
      price:400,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://buybooksindia.s3.amazonaws.com/2023/products/9788124317471-1688731102.jpg',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Fiction','Children','Cindrella','Navneet'],
    },

    {
      name:'Grandma Tales',
        id:'204',
        author:['Lalitha Iyer'],
        publisher:'Penguin Random House',
        price:250,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'https://buybooksindia.s3.amazonaws.com/2023/products/9789352751655-1688731185.jpg',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Fiction','Children','Grandma Tales','Lalitha Iyer'],
      },

      {
        name:'Little Red Riding Hood',
          id:'205',
          author:['Navneet'],
          publisher:'LiFi Publications Pvt Ltd',
          price:350,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'https://buybooksindia.s3.amazonaws.com/2023/products/9788124317464-1688731102.jpg',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Fiction','Children','Little Red Riding Hood','Navneet'],
        },

        
    //----------------Non-Fiction Book------------------------------------------
    //----------------History Book----------------------------------------------
    {
      name:'The Last Queen',
      id:'201',
      author:['Chitra Banerjee'],
      publisher:'Penguin Random House',
      price:300,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://cms.buybooksindia.com/uploads/books/9789390351954_0_1607758309.jpeg',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Non-Fiction','History','The Last Queen','Chitra Banerjee'],
    },
    {
      name:'The Aryabhata Clan',
      id:'202',
      author:['Sudipto Das'],
      publisher:'Penguin Random House',
      price:350,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://cms.buybooksindia.com/uploads/books/9789386906137_0_1607684864.jpeg',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Non-Fiction','History','The Aryabhata Clan','Sudipto Das'],
    },
    {
    name:'Secret of the Nagas',
      id:'203',
      author:['Amish Tripathi'],
      publisher:'Penguin Random House',
      price:400,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://cms.buybooksindia.com/uploads/books/9789381626344_0_1608275601.jpeg',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Non-Fiction','History','Secret of the Nagas','Amish Tripathi'],
    },

    {
      name:'Man with the White Beard',
        id:'204',
        author:['Shah Alam Khan'],
        publisher:'Penguin Random House',
        price:250,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'https://cms.buybooksindia.com/uploads/books/9789386191342_0_1608272175.jpeg',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Non-Fiction','History','Man with the White Beard','Shah Alam Khan'],
      },

      {
        name:'Devastating Hate',
          id:'205',
          author:['Markus Heitz'],
          publisher:'LiFi Publications Pvt Ltd',
          price:350,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'https://cms.buybooksindia.com/uploads/books/9781782065913_0_1611549001.jpeg',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Non-Fiction','History','Devastating Hate','Markus Heitz'],
        },

        
    //-----------------------Biography -------------------------------

    {
      name:'My Inventions,Autobiography of Nikola Tesla',
      id:'201',
      author:['Nikola Tesla'],
      publisher:'Penguin Random House',
      price:300,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/71pGZBofMGL._AC_UY218_.jpg',
      aboutTheBook:'"Romeo and Juliet" is a tragic love story written by William Shakespeare. It revolves around two young lovers, Romeo and Juliet, who come from feuding families. They fall deeply in love but face numerous obstacles due to their families ongoing conflict. In a desperate attempt to be together, they secretly marry with the help of Friar Laurence. However, a series of misunderstandings and tragic events unfold, leading to their untimely deaths. The play explores themes of love, fate, and the destructive power of hate. It is a timeless tale of passion, sacrifice, and the consequences of impulsive actions.',
      aboutTheAuthor:'William Shakespeare was an English playwright, poet, and actor who lived from 1564 to 1616. He is widely regarded as one of the greatest writers in the English language. Shakespeare wrote numerous plays and sonnets that explore themes of love, power, and human nature. His works, including "Romeo and Juliet," "Hamlet," and "Macbeth," continue to be celebrated for their profound insights and enduring impact on literature and theater. Shakespeare language and storytelling abilities have made him an iconic figure in the world of literature',
      reviews:'No review Found',
      tags:['Non-Fiction','Biography','My Inventions,Autobiography of Nikola Tesla','Nikola Tesla'],
    },
    {
      name:'The 1diary of a Young Girl',
      id:'202',
      author:['Anne Frank'],
      publisher:'Penguin Random House',
      price:350,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/81lZ-9E4F-S._AC_UY218_.jpg',
      aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
      aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
      reviews:'No review Found',
      tags:['Non-Fiction','Biography','The 1dairy of a Young Girl','Anne Frank'],
    },
    {
    name:'Wings of Fire',
      id:'203',
      author:['A.P.J.Abdul Kalam'],
      publisher:'Penguin Random House',
      price:400,
      availability:'Availabilty',
      shippingtime:'Usually ships 1-3 Days',
      favorite:false,
      star :5.0,
      imageUrl:'https://m.media-amazon.com/images/I/71KKZlVjbwL._AC_UY218_.jpg',
      aboutTheBook:'Meera, a fledgling writer who is in search of a story that can touch millions of lives.Vivaan, assistant branch manager at Citibank, who dreams of travelling the world.Kabir, a café manager who desires something of his own. Nisha, the despondent café customer who keeps secrets of her own.Everyone has their own story, but what happens when these four lives are woven together?Pull up a chair in Kafe Kabir and watch them explore friendship and love, writing their own pages of life from the cosy café to the ends of the world.',
      aboutTheAuthor:'A simple girl from Surat, Savi Sharma is the co-founder of the motivational media blog Life and People. Everyone Has a Story is her debut novel inspired by stories around her. ',
      reviews:'No review Found',
      tags:['Non-Fiction','Biography','Wings of Fire ','A.P.J.Abdul Kalam'],
    },

    {
      name:'Brief History Of Time',
        id:'204',
        author:['Stephen Hawking'],
        publisher:'Penguin Random House',
        price:250,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'https://m.media-amazon.com/images/I/81DBK93b6jL._AC_UY218_.jpg',
        aboutTheBook:'Love is that which inspires us. Love is that which makes us believe in miracles. Love is that changes one to be a good human being. Karan and Vandana, two teenagers were mad and made for each other. How does love inspire them? How does love make them believe in destiny? How does love change their world... Find in I will never find another U',
        aboutTheAuthor:'Kumar Kaustubh is an engineering student, lives in Jamshedpur. He has written 4 novels and scripts for many short films. He aspires to be an adventure traveller.',
        reviews:'No review Found',
        tags:['Non-Fiction','Biography','Brief History Of Time','Stephen Hawking'],
      },

      {
        name:'The Wings of Destiny',
          id:'205',
          author:['Molly Odegard Nikolic'],
          publisher:'LiFi Publications Pvt Ltd',
          price:350,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'https://m.media-amazon.com/images/I/316ckew-kvL._SY466_.jpg',
          aboutTheBook:'With You... Without You... is set in the 90’s Calcutta, with its main protagonist Jags, Ishika and Karan dealing with a plethora of school-life problems starting from board exams to relationship issues. It is a coming of age tale on how the inseparable trio gets lost in the melee of the world soon after school life ends, only to be united decades later. Everyone who loves their school life would be able to relate to this story written in a very lucid manner.',
          aboutTheAuthor:'Born in the Calcutta of 80s, he has spent a little over a decade sailing around the globe. This book was conceived during one such voyage where he had set out to conquer a new land. Apart from writing, he has a keen interest in touching peoples life and bring a smile on their faces.',
          reviews:'No review Found',
          tags:['Non-Fiction','Biography','The Wings of Destiny','Molly Odegard Nikolic'],
        },

        
    //School Book

    {
      name:'Marriage Without Marriage',
        id:'1001',
        author:['S.K.Sood'],
        publisher:'Penguin Random House',
        price:300,
        availability:'Availabilty',
        shippingtime:'Usually ships 1-3 Days',
        favorite:false,
        star :5.0,
        imageUrl:'/assets/Romance/r9.jpeg',
        aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
        aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
        reviews:'No review Found',
        tags:['School Education','Marriage Without Marriage','S.K.Sood'],
      },
      {
        name:'Marriage Without Marriage',
          id:'1002',
          author:['S.K.Sood'],
          publisher:'Penguin Random House',
          price:250,
          availability:'Availabilty',
          shippingtime:'Usually ships 1-3 Days',
          favorite:false,
          star :5.0,
          imageUrl:'/assets/Romance/r9.jpeg',
          aboutTheBook:'Lavanya Gogoi is from the scenic hills of Shillong while Rajveer Saini belongs to the shahi city of Patiala. Worlds apart from one another, the two land up next to each other on a flight from Mumbai to Chandigarh. Its love at first flight, at least for one of them. For the other . . . well, its going to take more than a plane ride!',
          aboutTheAuthor:'Ravinder Singh was born in a Sikh family in Kolkata in the year 1982. He spent 25 years of his life in Burla, Odisha. Having worked with some of Indias prominent IT companies, Singh graduated with a Masters in Business Administration from the reputed Indian School of Business. Singh previously wrote I Too Had a Love Story, which was released in the year 2008. The author interacts with his fans through his official Facebook page and enjoys Punjabi music when he is not busy working on his novels.',
          reviews:'No review Found',
          tags:['School Education','Marriage Without Marriage','S.K.Sood'],
        },
    ];
  }
}
